title:              juuc의 개발 일지
email:              ju.woocheol@gmail.com
description:        리액트 네이티브를 주로 다룹니다.
author:             juuc
baseurl:            ""
url:                "https://juuc.github.io"

# Social Profiles
twitter_username:   
github_username:    juuc
facebook_username:  
instagram_username:  ucheolju
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
